In [1]:
import pandas as pd

## Input Rating Data

In [2]:
df_input = pd.read_csv('user_rating_input.csv')
df_input.rename(columns={df_input.columns[0]: 'User'},inplace=True)
df_input.iloc[:, 0] = ['User_1', 'User_2', 'User_3', 'User_4']
df_input.set_index('User')

Vietnamese-Style Spaghetti Squash “Noodle” Bowls with Skirt Steak   \
User                                                                         
User_1                                                NaN                    
User_2                                                NaN                    
User_3                                                4.0                    
User_4                                                NaN                    

        Freeform Chicken Meatballs with Carrots and Yogurt Sauce   \
User                                                                
User_1                                                NaN           
User_2                                                NaN           
User_3                                                NaN           
User_4                                                3.0           

        Grain Bowls with Chicken, Spiced Chickpeas, and Avocado   \
User                                                               
User_1                                                NaN          
User_2                                                3.0          
User_3                                                2.0          
User_4                                                2.0          

        Ancho Chile Pork Tenderloin with Brussels Sprouts and Squash   \
User                                                                    
User_1                                                NaN               
User_2                                                5.0               
User_3                                                2.0               
User_4                                                NaN               

        Shrimp with Herby White Beans and Tomatoes   \
User                                                  
User_1                                          1.0   
User_2                                          2.0   
User_3                                          NaN   
User_4                                          3.0   

        Quick Sweet and Sour Chicken   Cacio e Pepe Pie   \
User                                                       
User_1                            2.0                NaN   
User_2                            4.0                2.0   
User_3                            2.0                NaN   
User_4                            NaN                2.0   

        Sunday Stash Sweet Potatoes   \
User                                   
User_1                           NaN   
User_2                           1.0   
User_3                           1.0   
User_4                           2.0   

        Chickpea Salad Sandwich with Creamy Carrot-Radish Slaw   \
User                                                              
User_1                                                NaN         
User_2                                                4.0         
User_3                                                NaN         
User_4                                                NaN         

        Mexican Meat Patties with Fresh Corn Salsa   ...  \
User                                                 ...   
User_1                                          NaN  ...   
User_2                                          1.0  ...   
User_3                                          1.0  ...   
User_4                                          4.0  ...   

        Roasted Garlic Herb Sauce   Herby Chicken Kofta Meatballs   \
User                                                                 
User_1                         NaN                             NaN   
User_2                         2.0                             4.0   
User_3                         5.0                             NaN   
User_4                         NaN                             5.0   

        Grilled Cheese Tacos   Salmon Burgers with Red Pepper Mayo   \
User                                                                  
User_1          

## Output Rating Data

In [3]:
df_output = pd.read_csv('user_rating_output.csv')
df_output.rename(columns={df_output.columns[0]: 'User'},inplace=True)
df_output.iloc[:, 0] = ['User_1', 'User_2', 'User_3', 'User_4']
df_output.set_index('User')

Vietnamese-Style Spaghetti Squash “Noodle” Bowls with Skirt Steak  \
User                                                                        
User_1                                           1.657521                   
User_2                                           4.027109                   
User_3                                           4.000000                   
User_4                                           3.502780                   

        Freeform Chicken Meatballs with Carrots and Yogurt Sauce  \
User                                                               
User_1                                           2.277013          
User_2                                           0.819706          
User_3                                           1.400869          
User_4                                           3.000000          

        Grain Bowls with Chicken, Spiced Chickpeas, and Avocado  \
User                                                              
User_1                                           1.350258         
User_2                                           3.000000         
User_3                                           2.000000         
User_4                                           2.000000         

        Ancho Chile Pork Tenderloin with Brussels Sprouts and Squash  \
User                                                                   
User_1                                           2.277013              
User_2                                           5.000000              
User_3                                           2.000000              
User_4                                           2.277013              

        Shrimp with Herby White Beans and Tomatoes  \
User                                                 
User_1                                    1.000000   
User_2                                    2.000000   
User_3                                    2.557042   
User_4                                    3.000000   

        Quick Sweet and Sour Chicken  Cacio e Pepe Pie  \
User                                                     
User_1                      2.000000          0.650277   
User_2                      4.000000          2.000000   
User_3                      2.000000          2.052315   
User_4                      1.257801          2.000000   

        Sunday Stash Sweet Potatoes  \
User                                  
User_1                     2.277013   
User_2                     1.000000   
User_3                     1.000000   
User_4                     2.000000   

        Chickpea Salad Sandwich with Creamy Carrot-Radish Slaw  \
User                                                             
User_1                                           2.738069        
User_2                                           4.000000        
User_3                                           3.552258        
User_4                                           1.847545        

        Mexican Meat Patties with Fresh Corn Salsa  ...  \
User                                                ...   
User_1                                    2.277013  ...   
User_2                                    1.000000  ...   
User_3                                    1.000000  ...   
User_4                                    4.000000  ...   

        Roasted Garlic Herb Sauce  Herby Chicken Kofta Meatballs  \
User                                                               
User_1                   2.277013                       0.631837   
User_2                   2.000000                       4.000000   
User_3                   5.000000                       4.361267   
User_4                   2.277013                       5.000000   

        Grilled Cheese Tacos  Salmon Burgers with Red Pepper Mayo  \
User                                                                
User_1                     3                                    2   
User_2                 

In [4]:
df = pd.DataFrame(df_output.mean(axis = 0))
df = df.transpose()
df.rename(index={0: 'Mean of 4 users'}).round(2)

Vietnamese-Style Spaghetti Squash “Noodle” Bowls with Skirt Steak  \
Mean of 4 users                                                3.3                   

                 Freeform Chicken Meatballs with Carrots and Yogurt Sauce  \
Mean of 4 users                                               1.87          

                 Grain Bowls with Chicken, Spiced Chickpeas, and Avocado  \
Mean of 4 users                                               2.09         

                 Ancho Chile Pork Tenderloin with Brussels Sprouts and Squash  \
Mean of 4 users                                               2.89              

                 Shrimp with Herby White Beans and Tomatoes  \
Mean of 4 users                                        2.14   

                 Quick Sweet and Sour Chicken  Cacio e Pepe Pie  \
Mean of 4 users                          2.31              1.68   

                 Sunday Stash Sweet Potatoes  \
Mean of 4 users                         1.57   

                 Chickpea Salad Sandwich with Creamy Carrot-Radish Slaw  \
Mean of 4 users                                               3.03        

                 Mexican Meat Patties with Fresh Corn Salsa  ...  \
Mean of 4 users                                        2.07  ...   

                 Roasted Garlic Herb Sauce  Herby Chicken Kofta Meatballs  \
Mean of 4 users                       2.89                            3.5   

                 Grilled Cheese Tacos  Salmon Burgers with Red Pepper Mayo  \
Mean of 4 users                  2.25                                  2.0   

                 Lentil and Chicken Soup with Sweet Potatoes and Escarole  \
Mean of 4 users                                               2.57          

                 10-Minute Chicken Flatbreads with Hummus and Yogurt  \
Mean of 4 users                                               0.82     

                 Sausage and Greens Sheet-Pan Dinner  White Chicken Chili  \
Mean of 4 users                                 1.57                  3.5   

                 One-Pot Curried Cauliflower with Couscous and Chickpeas  \
Mean of 4 users                                               3.44         

                 Hummus Dinner Bowls with Spiced Ground Beef and Tomatoes  
Mean of 4 users                                               3.28         

[1 rows x 103 columns]

## Receipe Information

In [5]:
df_all_info = pd.read_csv('all_info.csv')
df_all_info = df_all_info.drop(df_all_info.columns[0], axis = 1)
df_all_info

title  rating  calories  \
0    Vietnamese-Style Spaghetti Squash “Noodle” Bow...     4.5     503.0   
1    Freeform Chicken Meatballs with Carrots and Yo...     4.5     488.0   
2    Grain Bowls with Chicken, Spiced Chickpeas, an...     4.5    1448.0   
3    Ancho Chile Pork Tenderloin with Brussels Spro...     4.5     620.0   
4          Shrimp with Herby White Beans and Tomatoes      4.5     578.0   
..                                                 ...     ...       ...   
98   10-Minute Chicken Flatbreads with Hummus and Y...     4.5     463.0   
99                Sausage and Greens Sheet-Pan Dinner      4.5     665.0   
100                               White Chicken Chili      5.0     534.0   
101  One-Pot Curried Cauliflower with Couscous and ...     4.5     606.0   
102  Hummus Dinner Bowls with Spiced Ground Beef an...     4.5     329.0   

     sodium    fat  protein   price  cooking_time  \
0    1574.0   34.0     29.0   2.120          75.0   
1     985.0   32.0     29.0   9.889          45.0   
2     784.0  102.0     56.0   7.759          20.0   
3    1482.0   31.0     53.0   2.780          45.0   
4    1151.0   23.0     34.0   2.260          20.0   
..      ...    ...      ...     ...           ...   
98    917.0   18.0     35.0   3.839          10.0   
99    855.0   63.0     17.0   8.862          25.0   
100   968.0   14.0     45.0   6.839          30.0   
101  1365.0   15.0     27.0   9.208          45.0   
102   327.0   26.0     20.0  10.070          20.0   

                                       personal_rating  \
0    [['lfox18 from Ballston Lake, NY ', 5], ['hair...   
1    [['smallbluebird from SF Bay Area  ', 5], ['en...   
2    [['Anna D from San Diego, CA ', 4], ['alenarz ...   
3    [['zoeycooks from Boston, MA  ', 4], ['enietup...   
4    [['flagg ', 5], ['delaniepope from Grand Rapid...   
..                                                 ...   
98   [['maurini from Galveston, TX ', 5], ['joyq.ca...   
99   [['marywayland ', 3], ['blwyxx4163 from Durang...   
100  [['lmanderson from Maryland ', 5], ["debkane f...   
101  [['mkopke from Toronto, Canada ', 4], ['akraem...   
102  [['bradley2 from Foodietown, ,PA ', 4], ['chau...   

                                           ingredients  \
0    1 pound skirt steak, cut crosswise into 4-inch...   
1    5 Tbsp. extra-virgin olive oil, divided, plus ...   
2    ⅛ teaspoon cayenne pepper 6 tablespoons fresh ...   
3    2 pork tenderloins (about 1 pound each) 1 1/2 ...   
4    Thick slices of crusty toasted bread (for serv...   
..                                                 ...   
98   1/4 cup parsley leaves (optional) 1 teaspoon g...   
99   1¾ tsp. kosher salt, divided 3 Tbsp. sherry or...   
100  2 (15-ounce) cans white beans (such as Great N...   
101  3 large garlic cloves, coarsely chopped 1/4 cu...   
102  1 pint cherry tomatoes or 2 medium heirloom or...   

                                              keywords  
0    wheat/gluten-free soy free cucumber steak tree...  
1    lemon juice small plates quick & easy web spri...  
2    30 days of groceries lunch cucumber wheat/glut...  
3    wheat/gluten-free chile brussels sprout lime f...  
4    #cook90 quick and healthy tomato quick & easy ...  
..                                                 ...  
98   kid-friendly cucumber hummus quick and healthy...  
99   collard greens wheat/gluten-free kid-friendly ...  
100  wheat/gluten-free kid-friendly small plates ga...  
101  quick and healthy vegetarian spinach no meat, ...  
102  after beef kid-friendly lemon juice hummus par...  

[103 rows x 11 columns]

In [6]:
df_all_info = pd.read_csv('all_info.csv')
df_all_info = df_all_info.drop(df_all_info.columns[0], axis = 1)
df_all_info

title  rating  calories  \
0    Vietnamese-Style Spaghetti Squash “Noodle” Bow...     4.5     503.0   
1    Freeform Chicken Meatballs with Carrots and Yo...     4.5     488.0   
2    Grain Bowls with Chicken, Spiced Chickpeas, an...     4.5    1448.0   
3    Ancho Chile Pork Tenderloin with Brussels Spro...     4.5     620.0   
4          Shrimp with Herby White Beans and Tomatoes      4.5     578.0   
..                                                 ...     ...       ...   
98   10-Minute Chicken Flatbreads with Hummus and Y...     4.5     463.0   
99                Sausage and Greens Sheet-Pan Dinner      4.5     665.0   
100                               White Chicken Chili      5.0     534.0   
101  One-Pot Curried Cauliflower with Couscous and ...     4.5     606.0   
102  Hummus Dinner Bowls with Spiced Ground Beef an...     4.5     329.0   

     sodium    fat  protein   price  cooking_time  \
0    1574.0   34.0     29.0   2.120          75.0   
1     985.0   32.0     29.0   9.889          45.0   
2     784.0  102.0     56.0   7.759          20.0   
3    1482.0   31.0     53.0   2.780          45.0   
4    1151.0   23.0     34.0   2.260          20.0   
..      ...    ...      ...     ...           ...   
98    917.0   18.0     35.0   3.839          10.0   
99    855.0   63.0     17.0   8.862          25.0   
100   968.0   14.0     45.0   6.839          30.0   
101  1365.0   15.0     27.0   9.208          45.0   
102   327.0   26.0     20.0  10.070          20.0   

                                       personal_rating  \
0    [['lfox18 from Ballston Lake, NY ', 5], ['hair...   
1    [['smallbluebird from SF Bay Area  ', 5], ['en...   
2    [['Anna D from San Diego, CA ', 4], ['alenarz ...   
3    [['zoeycooks from Boston, MA  ', 4], ['enietup...   
4    [['flagg ', 5], ['delaniepope from Grand Rapid...   
..                                                 ...   
98   [['maurini from Galveston, TX ', 5], ['joyq.ca...   
99   [['marywayland ', 3], ['blwyxx4163 from Durang...   
100  [['lmanderson from Maryland ', 5], ["debkane f...   
101  [['mkopke from Toronto, Canada ', 4], ['akraem...   
102  [['bradley2 from Foodietown, ,PA ', 4], ['chau...   

                                           ingredients  \
0    1 pound skirt steak, cut crosswise into 4-inch...   
1    5 Tbsp. extra-virgin olive oil, divided, plus ...   
2    ⅛ teaspoon cayenne pepper 6 tablespoons fresh ...   
3    2 pork tenderloins (about 1 pound each) 1 1/2 ...   
4    Thick slices of crusty toasted bread (for serv...   
..                                                 ...   
98   1/4 cup parsley leaves (optional) 1 teaspoon g...   
99   1¾ tsp. kosher salt, divided 3 Tbsp. sherry or...   
100  2 (15-ounce) cans white beans (such as Great N...   
101  3 large garlic cloves, coarsely chopped 1/4 cu...   
102  1 pint cherry tomatoes or 2 medium heirloom or...   

                                              keywords  
0    wheat/gluten-free soy free cucumber steak tree...  
1    lemon juice small plates quick & easy web spri...  
2    30 days of groceries lunch cucumber wheat/glut...  
3    wheat/gluten-free chile brussels sprout lime f...  
4    #cook90 quick and healthy tomato quick & easy ...  
..                                                 ...  
98   kid-friendly cucumber hummus quick and healthy...  
99   collard greens wheat/gluten-free kid-friendly ...  
100  wheat/gluten-free kid-friendly small plates ga...  
101  quick and healthy vegetarian spinach no meat, ...  
102  after beef kid-friendly lemon juice hummus par...  

[103 rows x 11 columns]

In [7]:
df_all_info.shape

(103, 11)

## Cook Ability

In [8]:
df_cook_ability = pd.read_csv('cook_ability.csv')
df_cook_ability = df_cook_ability.drop(df_cook_ability.columns[0], axis = 1)
df_cook_ability.set_index(df_all_info['title'])

User 1  User 2  User 3  \
title                                                                        
Vietnamese-Style Spaghetti Squash “Noodle” Bowl...       0       1       1   
Freeform Chicken Meatballs with Carrots and Yog...       1       1       1   
Grain Bowls with Chicken, Spiced Chickpeas, and...       1       1       1   
Ancho Chile Pork Tenderloin with Brussels Sprou...       1       1       1   
Shrimp with Herby White Beans and Tomatoes               1       1       1   
...                                                    ...     ...     ...   
10-Minute Chicken Flatbreads with Hummus and Yo...       1       1       0   
Sausage and Greens Sheet-Pan Dinner                      1       1       1   
White Chicken Chili                                      1       1       1   
One-Pot Curried Cauliflower with Couscous and C...       1       0       1   
Hummus Dinner Bowls with Spiced Ground Beef and...       1       1       1   

                                                    User 4  
title                                                       
Vietnamese-Style Spaghetti Squash “Noodle” Bowl...       1  
Freeform Chicken Meatballs with Carrots and Yog...       1  
Grain Bowls with Chicken, Spiced Chickpeas, and...       1  
Ancho Chile Pork Tenderloin with Brussels Sprou...       1  
Shrimp with Herby White Beans and Tomatoes               1  
...                                                    ...  
10-Minute Chicken Flatbreads with Hummus and Yo...       1  
Sausage and Greens Sheet-Pan Dinner                      1  
White Chicken Chili                                      1  
One-Pot Curried Cauliflower with Couscous and C...       1  
Hummus Dinner Bowls with Spiced Ground Beef and...       1  

[103 rows x 4 columns]

In [9]:
print(df_cook_ability['User 1'].tolist())

[0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1]


## Dislike food

In [10]:
df_all_info[df_all_info['ingredients'].str.contains('coriander')].index

Int64Index([11, 44, 46, 94, 102], dtype='int64')

In [11]:
df_all_info[df_all_info['ingredients'].str.contains('celery')].index

Int64Index([97], dtype='int64')

In [12]:
df_all_info[df_all_info['ingredients'].str.contains('broccoli')].index

Int64Index([18, 31, 38, 43, 51, 88], dtype='int64')

In [13]:
dislike = []
for i in range(103):
    dislike.append(1)

In [14]:
dislike_list = [11, 44, 46, 94, 102, 97, 18, 31, 38, 43, 51, 88]
for i in dislike_list:
    dislike[i] = 0

In [15]:
print(dislike)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0]


In [16]:
import json
  
# Opening JSON file
f = open('/Users/stella/Downloads/Fall 2022/ISE 533/Project 1/Provided/recipe_scraping/result.json')
  
# returns JSON object as 
# a dictionary
data = json.load(f)
data

[{'title': 'Curried Lentil, Tomato, and Coconut Soup ',
  'rating': 5.0,
  'calories': 437.0,
  'sodium': 667.0,
  'fat': 28.0,
  'protein': 13.0,
  'personal_rating': [['rhaeredekop from Winnipeg, MB ', 5],
   ['lizgoldsmith1960 from Lincoln, MA ', 5],
   ['bmaybeegeorge from Canada', 5],
   ['adventurousz from Boulder, CO ', 3],
   ['epaul77 from Mississippi ', 5],
   ['lizzydlangley from St. Louis ', 5],
   ['Jweyant from Maine ', 5],
   ['tjsnuffin from Cincinnati, OH ', 5],
   ['sarahglittle7930 from Denver, CO ', 5],
   ['wendymochi from Torrance ', 5],
   ['ayydre from California ', 4],
   ['susanweiss from Rockville, MD ', 5],
   ['silvia_v from Belmont, MA ', 5],
   ['Tejanacooks from Texas ', 3],
   ['kevinj308 ', 5],
   ['cellocath85 from Maryland ', 5],
   ['mvross from Texas ', 5],
   ['lhdowney from Charlotte, NC ', 5],
   ['jsbjk from Winnetka, IL ', 4],
   ['karen8221 from Westchester County, NY ', 5],
   ['idesalos from Houston ', 5],
   ['colettestp from Montreal, Can

In [17]:
original_all_info = pd.DataFrame(data)
original_all_info

title  rating  calories  \
0            Curried Lentil, Tomato, and Coconut Soup      5.0     437.0   
1    Roasted Butternut Squash with Herb Oil and Goa...     4.5     175.0   
2                                     Pumpkin Muffins      4.0     364.0   
3    Chopped Salad with Shallot Vinaigrette, Feta, ...     5.0     170.0   
4    Grain Salad with Olives and Whole-Lemon Vinaig...     3.5     330.0   
..                                                 ...     ...       ...   
293  One-Pot Curried Cauliflower with Couscous and ...     4.5     606.0   
294                Acorn Squash with Kale and Sausage      4.5       NaN   
295  Hummus Dinner Bowls with Spiced Ground Beef an...     4.5     329.0   
296                                 Autumn Kale Salad      5.0     287.0   
297       Pumpkin Icebox Pie With Snickerdoodle Crust      4.5    3597.0   

     sodium    fat  protein                                    personal_rating  
0     667.0   28.0     13.0  [[rhaeredekop from Winnipeg, MB , 5], [lizgold...  
1     576.0    9.0      4.0  [[ilyssa2 from NY, NY , 5], [dory92064 from Sa...  
2     183.0   11.0      6.0  [[mtnmeye , 3], [greenstein.rebecca9820 from N...  
3     413.0   13.0      6.0  [[brushjl from solon, oh , 5], [tatyana_poirie...  
4     483.0   19.0      8.0  [[auntwebbie from Allen, TX , 5], [krf from Be...  
..      ...    ...      ...                                                ...  
293  1365.0   15.0     27.0  [[mkopke from Toronto, Canada , 4], [akraemer1...  
294     NaN    NaN      NaN  [[sminkoff , 3], [emdean from Madison, WI , 5]...  
295   327.0   26.0     20.0  [[bradley2 from Foodietown, ,PA , 4], [chaurie...  
296   329.0   22.0      4.0  [[dottie60 from Boston , 5], [zeta from Victor...  
297  1869.0  223.0     33.0  [[Lois33 from EGR, Michigan , 5], [mccoyj25 fr...  

[298 rows x 7 columns]

## Model 1 Result

In [18]:
import numpy as np
u11 = np.array([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
np.where(u11 == 1.0)

(array([29]),)

In [19]:
df_all_info.iloc[29]

title                                               Grain Bowl Soup 
rating                                                           3.5
calories                                                        1250
sodium                                                          1121
fat                                                               62
protein                                                           50
price                                                         16.023
cooking_time                                                      45
personal_rating    [['kdavidge from San Francisco, CA ', 5], ['bl...
ingredients        3/4 cup extra-virgin olive oil, divided 2 shal...
keywords           lemon juice soup/stew web parsley barley quino...
Name: 29, dtype: object

In [20]:
u12 = np.array([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
np.where(u12 == 1.0)

(array([94]),)

In [21]:
df_all_info.iloc[94]

title                                 Herby Chicken Kofta Meatballs 
rating                                                           4.5
calories                                                         137
sodium                                                           247
fat                                                                8
protein                                                           13
price                                                          7.779
cooking_time                                                      55
personal_rating    [['cinzedym from Arlington, VA ', 4], ['hartma...
ingredients        2 teaspoons kosher salt, divided 2 medium yell...
keywords           #cook90 parsley middle eastern coriander garli...
Name: 94, dtype: object

In [22]:
u13 = np.array([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
np.where(u13 == 1.0)

(array([58]),)

In [23]:
u24 = np.array([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
np.where(u24 == 1.0)

(array([44]),)

In [24]:
df_all_info.iloc[44]

title                             Easy Lamb Tagine with Pomegranate 
rating                                                           4.5
calories                                                         640
sodium                                                           573
fat                                                               49
protein                                                           39
price                                                           4.26
cooking_time                                                     120
personal_rating    [['gumboboy from Rochester NY ', 5], ['pghgrl ...
ingredients        1 teaspoon ground cumin 1 tablespoon mint leav...
keywords           braise wheat/gluten-free new year's eve corian...
Name: 44, dtype: object

In [25]:
u32 = np.array([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
np.where(u32 == 1.0)

(array([35]),)

In [26]:
df_all_info.iloc[35]

title              Pumpkin and Cookie-Butter Sheet Cake with Toas...
rating                                                           4.5
calories                                                         355
sodium                                                           243
fat                                                               18
protein                                                            5
price                                                           2.62
cooking_time                                                     120
personal_rating    [['acfisch from Cincinnati, OH ', 4], ['pdxgou...
ingredients        4 large egg whites 1 teaspoon vanilla extract ...
keywords           dessert thanksgiving soufflé/meringue bake cak...
Name: 35, dtype: object

In [27]:
u41 = np.array([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
np.where(u41 == 1.0)

(array([27]),)

In [28]:
df_all_info.iloc[27]

title                         Veggie Burgers with Zucchini and Corn 
rating                                                           3.5
calories                                                         708
sodium                                                           733
fat                                                               41
protein                                                           20
price                                                           5.25
cooking_time                                                      70
personal_rating    [['keritilman from Newport, RI ', 2], ['Maddie...
ingredients        2 tablespoons vegetable oil, divided, plus mor...
keywords           wheat/gluten-free vegan zucchini back to schoo...
Name: 27, dtype: object

In [29]:
u43 = np.array([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
np.where(u43 == 1.0)

(array([78]),)

In [30]:
df_all_info.iloc[78]

title                                Big-Batch Seasoned Ground Beef 
rating                                                             1
calories                                                         260
sodium                                                           428
fat                                                               11
protein                                                           39
price                                                          12.59
cooking_time                                                      25
personal_rating                                                   []
ingredients        2 Tbsp. extra-virgin olive oil 4 tsp. kosher s...
keywords           kid-friendly small plates ground beef web beef...
Name: 78, dtype: object

In [31]:
u44 = np.array([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
np.where(u44 == 1.0)

(array([93]),)

In [32]:
df_all_info.iloc[93]

title                                     Roasted Garlic Herb Sauce 
rating                                                             5
calories                                                         693
sodium                                                           388
fat                                                               73
protein                                                            3
price                                                           6.53
cooking_time                                                      20
personal_rating    [['sue99 from Canada ', 5], ['zivameira from M...
ingredients        3/4 teaspoon kosher salt 2 cups (packed) parsl...
keywords           #cook90 parsley lemon garlic quick & easy web ...
Name: 93, dtype: object

In [33]:
df_model1 = df_all_info.iloc[[29,94,58,44,35,27,78,93],:]
df_model1.loc['Column_Total']= df_model1.sum(numeric_only=True, axis=0)
df_model1

/Users/stella/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:670: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)


title  rating  \
29                                             Grain Bowl Soup      3.5   
94                               Herby Chicken Kofta Meatballs      4.5   
58            Easy Green Curry with Chicken, Bell Pepper, an...     4.5   
44                           Easy Lamb Tagine with Pomegranate      4.5   
35            Pumpkin and Cookie-Butter Sheet Cake with Toas...     4.5   
27                       Veggie Burgers with Zucchini and Corn      3.5   
78                              Big-Batch Seasoned Ground Beef      1.0   
93                                   Roasted Garlic Herb Sauce      5.0   
Column_Total                                                NaN    31.0   

              calories  sodium    fat  protein   price  cooking_time  \
29              1250.0  1121.0   62.0     50.0  16.023          45.0   
94               137.0   247.0    8.0     13.0   7.779          55.0   
58               549.0   760.0   36.0     42.0   9.139          20.0   
44               640.0   573.0   49.0     39.0   4.260         120.0   
35               355.0   243.0   18.0      5.0   2.620         120.0   
27               708.0   733.0   41.0     20.0   5.250          70.0   
78               260.0   428.0   11.0     39.0  12.590          25.0   
93               693.0   388.0   73.0      3.0   6.530          20.0   
Column_Total    4592.0  4493.0  298.0    211.0  64.191         475.0   

                                                personal_rating  \
29            [['kdavidge from San Francisco, CA ', 5], ['bl...   
94            [['cinzedym from Arlington, VA ', 4], ['hartma...   
58            [['cbradbury from Silverton, OR  ', 4], ['egar...   
44            [['gumboboy from Rochester NY ', 5], ['pghgrl ...   
35            [['acfisch from Cincinnati, OH ', 4], ['pdxgou...   
27            [['keritilman from Newport, RI ', 2], ['Maddie...   
78                                                           []   
93            [['sue99 from Canada ', 5], ['zivameira from M...   
Column_Total                                                NaN   

                                                    ingredients  \
29            3/4 cup extra-virgin olive oil, divided 2 shal...   
94            2 teaspoons kosher salt, divided 2 medium yell...   
58            1/2 pound sugar snap peas, trimmed (about 2 1/...   
44            1 teaspoon ground cumin 1 tablespoon mint leav...   
35            4 large egg whites 1 teaspoon vanilla extract ...   
27            2 tablespoons vegetable oil, divided, plus mor...   
78            2 Tbsp. extra-virgin olive oil 4 tsp. kosher s...   
93            3/4 teaspoon kosher salt 2 cups (packed) parsl...   
Column_Total                                                NaN   

                                                       keywords  
29            lemon juice soup/stew web parsley barley quino...  
94            #cook90 parsley middle eastern coriander garli...  
58            wheat/gluten-free soy free coconut quick & eas...  
44            braise wheat/gluten-free new year's eve corian...  
35            dessert thanksgiving soufflé/meringue bake cak...  
27            wheat/gluten-free vegan zucchini back to schoo...  
78            kid-friendly small plates ground beef web beef...  
93            #cook90 parsley lemon garlic quick & easy web ...  
Column_Total                                                NaN

## Model 2 Result

In [34]:
u1_1 = np.array([0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0, 0.0, 0.0, -0.0, -0.0, -0.0, -0.0, 0.0, 0.0, -0.0, -0.0, 0.0, 0.0, -0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.0, -0.0, 0.0, -0.0, -0.0, -0.0, 0.0, -0.0, 0.0, 0.0, 0.0, -0.0, -0.0, -0.0, 0.0, 0.0, -0.0, 0.0, 1.0, 0.0, -0.0, -0.0, 0.0, -0.0, -0.0, -0.0, 0.0, -0.0, -0.0, 0.0, -0.0, 0.0, -0.0, -0.0, 0.0, -0.0, -0.0, -0.0, 0.0, 0.0, -0.0, -0.0, 0.0, -0.0, 0.0, -0.0, -0.0, 0.0, 0.0, -0.0, -0.0, -0.0, -0.0, 0.0, -0.0, -0.0, 0.0, 0.0, -0.0, 0.0, -0.0, 0.0, -0.0, -0.0, 0.0, 0.0, -0.0, -0.0, 0.0, -0.0, -0.0, -0.0, -0.0, 0.0])
np.where(u1_1 == 1.0)

(array([47]),)

In [35]:
df_all_info.iloc[47]

title                                     The Winterized Penicillin 
rating                                                             4
calories                                                         959
sodium                                                            13
fat                                                                0
protein                                                            1
price                                                              0
cooking_time                                                      60
personal_rating    [['114Italianate from Johnstown, NY ', 5], ['t...
ingredients        3/4 cup honey 2 ounces blended scotch 1 (6") p...
keywords           house cocktail grapefruit drinks cocktail web ...
Name: 47, dtype: object

In [36]:
u1_4 = np.array([0.0, -0.0, 0.0, 0.0, 0.0, 0.0, -0.0, -0.0, 0.0, -0.0, 0.0, 0.0, -0.0, -0.0, -0.0, -0.0, -0.0, 0.0, 0.0, -0.0, -0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.0, -0.0, 0.0, -0.0, -0.0, -0.0, 0.0, -0.0, 0.0, 0.0, 0.0, -0.0, -0.0, -0.0, 0.0, 0.0, 0.0, 0.0, -0.0, 0.0, -0.0, 0.0, 0.0, -0.0, -0.0, -0.0, 0.0, -0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.0, -0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.0, -0.0, 0.0, -0.0, -0.0, -0.0, -0.0, 0.0, -0.0, -0.0, 0.0, -0.0, -0.0, 0.0, -0.0, 0.0, 0.0, -0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.0, 0.0, -0.0, 0.0, 0.0])
np.where(u1_4)

(array([23]),)

In [37]:
df_all_info.iloc[23]

title              Braised Rotisserie Chicken with Bacon, Tomatoe...
rating                                                             5
calories                                                         737
sodium                                                           708
fat                                                               50
protein                                                           52
price                                                         11.859
cooking_time                                                      30
personal_rating    [['502forestdrive4876 from Washington DC ', 5]...
ingredients        1 (14-ounce) can diced tomatoes 2 shallots, th...
keywords           30 days of groceries braise wheat/gluten-free ...
Name: 23, dtype: object

In [38]:
u2_1 = np.array([0.0, 0.0, -0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.0, 0.0, 0.0, -0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.0, -0.0, 0.0, -0.0, 0.0, 1.0, 0.0, -0.0, 0.0, 0.0, -0.0, -0.0, -0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.0, 0.0, 0.0, -0.0, -0.0, 0.0, -0.0, 0.0, 0.0, 0.0, -0.0, -0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.0, 0.0, -0.0, 0.0, 0.0, 0.0, 0.0, -0.0, 0.0, 0.0, 0.0, -0.0, -0.0, 0.0, 0.0, -0.0, 0.0, 0.0, 0.0, 0.0, -0.0, 0.0, 0.0, 0.0, 0.0])
np.where(u2_1)

(array([34]),)

In [39]:
df_all_info.iloc[34]

title              Persian-Spiced Chicken with Spaghetti Squash, ...
rating                                                           4.5
calories                                                         847
sodium                                                           953
fat                                                               62
protein                                                           46
price                                                          5.519
cooking_time                                                      60
personal_rating    [['marlysws from Phoenix, AZ ', 5], ['jellis14...
ingredients        4 tablespoons olive oil, divided 2 teaspoons g...
keywords           wheat/gluten-free soy free spice middle easter...
Name: 34, dtype: object

In [40]:
u2_2 = np.array([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.0, 0.0, 0.0, 0.0, -0.0, -0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.0, 0.0, 0.0, 0.0, -0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.0, 0.0, 0.0, 0.0, 0.0, -0.0, 0.0, 0.0, 0.0, -0.0, -0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, -0.0, 0.0, 0.0, 0.0, 0.0])
np.where(u2_2)

(array([93]),)

In [41]:
df_all_info.iloc[93]

title                                     Roasted Garlic Herb Sauce 
rating                                                             5
calories                                                         693
sodium                                                           388
fat                                                               73
protein                                                            3
price                                                           6.53
cooking_time                                                      20
personal_rating    [['sue99 from Canada ', 5], ['zivameira from M...
ingredients        3/4 teaspoon kosher salt 2 cups (packed) parsl...
keywords           #cook90 parsley lemon garlic quick & easy web ...
Name: 93, dtype: object

In [42]:
u3_2 = np.array([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.0, 0.0, -0.0, 0.0, -0.0, -0.0, -0.0, 0.0, 0.0, -0.0, 0.0, -0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.0, 0.0, 0.0, -0.0, -0.0, 0.0, -0.0, 0.0, 0.0, 0.0, 1.0, -0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.0, 0.0, 0.0, 0.0, -0.0, -0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
np.where(u3_2)

(array([62]),)

In [43]:
df_all_info.iloc[62]

title                                           French Spiced Bread 
rating                                                             4
calories                                                         337
sodium                                                           410
fat                                                                5
protein                                                            8
price                                                          14.63
cooking_time                                                      60
personal_rating    [['sue99 from Ottawa, canada ', 5], ['frecklep...
ingredients        1/2 cup whole almonds 2 tablespoons melted uns...
keywords           dessert soy free small plates almond party web...
Name: 62, dtype: object

In [44]:
u3_3 = np.array([0.0, -0.0, -0.0, -0.0, -0.0, -0.0, 0.0, -0.0, -0.0, -0.0, -0.0, 0.0, 0.0, -0.0, -0.0, -0.0, -0.0, 0.0, 0.0, -0.0, -0.0, 0.0, 0.0, -0.0, -0.0, 0.0, 0.0, -0.0, 0.0, -0.0, -0.0, 0.0, -0.0, -0.0, -0.0, 0.0, -0.0, 0.0, 0.0, 0.0, 0.0, -0.0, 0.0, 0.0, 0.0, -0.0, 0.0, -0.0, 0.0, 0.0, -0.0, 0.0, -0.0, -0.0, -0.0, 0.0, -0.0, -0.0, -0.0, -0.0, 0.0, -0.0, -0.0, 0.0, -0.0, -0.0, -0.0, -0.0, 0.0, -0.0, -0.0, 0.0, -0.0, 0.0, -0.0, -0.0, 0.0, 0.0, 1.0, 0.0, -0.0, -0.0, 0.0, -0.0, -0.0, -0.0, 0.0, -0.0, 0.0, 0.0, 0.0, -0.0, -0.0, 0.0, 0.0, -0.0, -0.0, 0.0, 0.0, -0.0, -0.0, -0.0, 0.0])
np.where(u3_3)

(array([78]),)

In [45]:
df_all_info.iloc[78]

title                                Big-Batch Seasoned Ground Beef 
rating                                                             1
calories                                                         260
sodium                                                           428
fat                                                               11
protein                                                           39
price                                                          12.59
cooking_time                                                      25
personal_rating                                                   []
ingredients        2 Tbsp. extra-virgin olive oil 4 tsp. kosher s...
keywords           kid-friendly small plates ground beef web beef...
Name: 78, dtype: object

In [46]:
u4_3 = np.array([-0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0, 0.0, 0.0, -0.0, -0.0, -0.0, -0.0, -0.0, 0.0, 0.0, -0.0, -0.0, 0.0, 0.0, -0.0, 0.0, 0.0, 0.0, 1.0, 0.0, -0.0, -0.0, 0.0, -0.0, -0.0, -0.0, 0.0, -0.0, 0.0, 0.0, 0.0, 0.0, -0.0, -0.0, 0.0, 0.0, -0.0, 0.0, 0.0, 0.0, 0.0, -0.0, 0.0, -0.0, -0.0, -0.0, 0.0, -0.0, -0.0, -0.0, -0.0, 0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0, 0.0, -0.0, -0.0, 0.0, 0.0, 0.0, -0.0, -0.0, -0.0, 0.0, -0.0, -0.0, -0.0, -0.0, 0.0, -0.0, -0.0, -0.0, 0.0, -0.0, 0.0, -0.0, -0.0, -0.0, -0.0, 0.0, 0.0, -0.0, -0.0, 0.0, -0.0, -0.0, -0.0, -0.0, 0.0])
np.where(u4_3)

(array([27]),)

In [47]:
df_all_info.iloc[27]

title                         Veggie Burgers with Zucchini and Corn 
rating                                                           3.5
calories                                                         708
sodium                                                           733
fat                                                               41
protein                                                           20
price                                                           5.25
cooking_time                                                      70
personal_rating    [['keritilman from Newport, RI ', 2], ['Maddie...
ingredients        2 tablespoons vegetable oil, divided, plus mor...
keywords           wheat/gluten-free vegan zucchini back to schoo...
Name: 27, dtype: object

In [48]:
u4_4 = np.array([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.0, -0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.0, 0.0, 0.0, -0.0, 0.0, -0.0, 0.0, -0.0, 0.0, -0.0, 0.0, 0.0, 0.0, 0.0, -0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.0, -0.0, -0.0, 0.0, -0.0, 0.0, 1.0, 0.0, 0.0, 0.0, -0.0, -0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.0, 0.0, 0.0, -0.0, 0.0, -0.0, 0.0, 0.0, 0.0, -0.0, -0.0, 0.0, 0.0, 0.0, -0.0, -0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.0, 0.0, 0.0, 0.0, 0.0])
np.where(u4_4)

(array([58]),)

In [49]:
df_all_info.iloc[58]

title              Easy Green Curry with Chicken, Bell Pepper, an...
rating                                                           4.5
calories                                                         549
sodium                                                           760
fat                                                               36
protein                                                           42
price                                                          9.139
cooking_time                                                      20
personal_rating    [['cbradbury from Silverton, OR  ', 4], ['egar...
ingredients        1/2 pound sugar snap peas, trimmed (about 2 1/...
keywords           wheat/gluten-free soy free coconut quick & eas...
Name: 58, dtype: object

In [50]:
df_model2 = df_all_info.iloc[[47,23,34,93,62,78,27,58],:]
df_model2.loc['Column_Total']= df_model2.sum(numeric_only=True, axis=0)
df_model2

/Users/stella/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:670: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)


title  rating  \
47                                   The Winterized Penicillin      4.0   
23            Braised Rotisserie Chicken with Bacon, Tomatoe...     5.0   
34            Persian-Spiced Chicken with Spaghetti Squash, ...     4.5   
93                                   Roasted Garlic Herb Sauce      5.0   
62                                         French Spiced Bread      4.0   
78                              Big-Batch Seasoned Ground Beef      1.0   
27                       Veggie Burgers with Zucchini and Corn      3.5   
58            Easy Green Curry with Chicken, Bell Pepper, an...     4.5   
Column_Total                                                NaN    31.5   

              calories  sodium    fat  protein   price  cooking_time  \
47               959.0    13.0    0.0      1.0   0.000          60.0   
23               737.0   708.0   50.0     52.0  11.859          30.0   
34               847.0   953.0   62.0     46.0   5.519          60.0   
93               693.0   388.0   73.0      3.0   6.530          20.0   
62               337.0   410.0    5.0      8.0  14.630          60.0   
78               260.0   428.0   11.0     39.0  12.590          25.0   
27               708.0   733.0   41.0     20.0   5.250          70.0   
58               549.0   760.0   36.0     42.0   9.139          20.0   
Column_Total    5090.0  4393.0  278.0    211.0  65.517         345.0   

                                                personal_rating  \
47            [['114Italianate from Johnstown, NY ', 5], ['t...   
23            [['502forestdrive4876 from Washington DC ', 5]...   
34            [['marlysws from Phoenix, AZ ', 5], ['jellis14...   
93            [['sue99 from Canada ', 5], ['zivameira from M...   
62            [['sue99 from Ottawa, canada ', 5], ['frecklep...   
78                                                           []   
27            [['keritilman from Newport, RI ', 2], ['Maddie...   
58            [['cbradbury from Silverton, OR  ', 4], ['egar...   
Column_Total                                                NaN   

                                                    ingredients  \
47            3/4 cup honey 2 ounces blended scotch 1 (6") p...   
23            1 (14-ounce) can diced tomatoes 2 shallots, th...   
34            4 tablespoons olive oil, divided 2 teaspoons g...   
93            3/4 teaspoon kosher salt 2 cups (packed) parsl...   
62            1/2 cup whole almonds 2 tablespoons melted uns...   
78            2 Tbsp. extra-virgin olive oil 4 tsp. kosher s...   
27            2 tablespoons vegetable oil, divided, plus mor...   
58            1/2 pound sugar snap peas, trimmed (about 2 1/...   
Column_Total                                                NaN   

                                                       keywords  
47            house cocktail grapefruit drinks cocktail web ...  
23            30 days of groceries braise wheat/gluten-free ...  
34            wheat/gluten-free soy free spice middle easter...  
93            #cook90 parsley lemon garlic quick & easy web ...  
62            dessert soy free small plates almond party web...  
78            kid-friendly small plates ground beef web beef...  
27            wheat/gluten-free vegan zucchini back to schoo...  
58            wheat/gluten-free soy free coconut quick & eas...  
Column_Total                                                NaN